baseURL = 'https://main.d1jtfhinlastnr.amplifyapp.com/'
languageCode = 'ja'
title = 'SmartWeb'
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["txt"]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.ROBOTS]
    mediaType = "text/plain"
    baseName = "robots"
    isPlainText = true
    notAlternative = true
    permalinkable = true
  [outputFormats.SITEMAP]
    mediaType = "application/xml"
    baseName = "sitemap"
    isPlainText = false
    isHTML = false
    noUgly = true
    rel = "sitemap"

[params]
  description = "次世代のWeb体験をあなたに"
  author = "SmartWeb"
  mainSections = ["blog"]
  dateFormat = "2006年1月2日"
  
  [params.imaging]
    resampleFilter = "Lanczos"
    quality = 85
    anchor = "smart"
    bgColor = "#ffffff"
    webpQuality = 85

[languages]
  [languages.ja]
    languageName = "日本語"
    title = "SmartWeb"
    weight = 1
    contentDir = "content/ja"
    [languages.ja.params]
      bcp47Lang = "ja"
      description = "次世代のWeb体験をあなたに"
    [[languages.ja.menu.main]]
      identifier = "home"
      name = "ホーム"
      url = "/"
      weight = 1
    [[languages.ja.menu.main]]
      identifier = "services"
      name = "サービス"
      url = "#"
      weight = 2
    [[languages.ja.menu.main]]
      identifier = "solutions"
      name = "ソリューション"
      url = "#"
      weight = 3
    [[languages.ja.menu.main]]
      identifier = "resources"
      name = "リソース"
      url = "#"
      weight = 4
    [[languages.ja.menu.main]]
      identifier = "blog"
      name = "ブログ"
      url = "/blog/"
      weight = 5
    [[languages.ja.menu.main]]
      identifier = "company"
      name = "会社情報"
      url = "#"
      weight = 6
  
  [languages.en]
    languageName = "English"
    title = "SmartWeb"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      bcp47Lang = "en-us"
      description = "Next generation web experience"
    [[languages.en.menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "services"
      name = "Services"
      url = "#"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "solutions"
      name = "Solutions"
      url = "#"
      weight = 3
    [[languages.en.menu.main]]
      identifier = "resources"
      name = "Resources"
      url = "#"
      weight = 4
    [[languages.en.menu.main]]
      identifier = "blog"
      name = "Blog"
      url = "/blog/"
      weight = 5
    [[languages.en.menu.main]]
      identifier = "company"
      name = "Company"
      url = "#"
      weight = 6

[taxonomies]
  tag = "tags"
  category = "categories"

[build]
  writeStats = true

[sitemap]
  filename = "sitemap.xml"
